apiVersion: v1
kind: Namespace
metadata:
  name: moirai
  labels:
    name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: moirai
  labels:
    app: sentiment-analysis
  name: sentiment-analysis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec: 
      containers:
      - image: pmhalvor/sentiment-analysis
        name: sentiment-analysis
---
apiVersion: v1
kind: Service
metadata:
  namespace: moirai
  labels:
    app: sentiment-analysis
  name: sentiment-analysis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentiment-analysis
  type: LoadBalancer
