apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: sentiment-analysis
  name: sentiment-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec: 
      containers:
      - image: pmhalvor/sentiment-analysis
        name: sentiment-analysis
        env:
          - name: bert_state_dict
            value: models/SA_bert_state_dict.pt
          - name: bert_params
            value: models/SA_bert_params.pt
          - name: bert_score
            value: models/SA_bert_score.pt
          - name: CLOUD_STORAGE_BUCKET
            value: gcp-terraform-pytorch-bucket-1
          - name: glass_animals
            value: toes
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: sentiment-analysis
  name: sentiment-analysis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: sentiment-analysis
  type: LoadBalancer
